/*

   jueves, 05 de agosto de 2004 13:06:21

   Usuario: sa

   Servidor: SATURNO

   Base de datos: Matricula

   Aplicación: MS SQLEM - Data Tools

*/



BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE matricula.RA_OPINTERNET ADD
	HABILITADA varchar(1) NULL
GO
COMMIT
