<%

  'Conn.Close()
 
'Set conn = Server.CreateObject("ADODB.Connection")
'conn.open "PROVIDER=SQLOLEDB;DATA SOURCE=192.168.220.43,4473;UID=matricula;PWD=dtb01s;DATABASE=pruebas"

'conn.open "PROVIDER=SQLOLEDB;DATA SOURCE=10.0.0.253;UID=matricula;PWD=dtb01s;DATABASE=Matricula"

'sConn =	"DRIVER={SQL SERVER};SERVER=" & cStr(Application("Servidor")) & _
'			";UID=" & cStr(Application("Usuario")) & _
'			";PWD=" & cStr(Application("password")) & _
'			";DATABASE=" & cStr(Application("Base")) & ";"
'
'	Set cOnn = Server.CreateObject("ADODB.Connection")
'	conn.open sConn

%>
